# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\nbtv.llm.v1\"\x97\x01\n\nLlmRequest\x12\r\n\x05model\x18\x01 \x01(\t\x12\x15\n\rmessages_json\x18\x02 \x01(\t\x12\x18\n\x0btemperature\x18\x03 \x01(\x01H\x00\x88\x01\x01\x12\x17\n\nmax_tokens\x18\x04 \x01(\rH\x01\x88\x01\x01\x12\x11\n\trequester\x18\x05 \x01(\tB\x0e\n\x0c_temperatureB\r\n\x0b_max_tokens\"`\n\x08LlmChunk\x12\x14\n\ntext_delta\x18\x01 \x01(\tH\x00\x12\"\n\x05usage\x18\x02 \x01(\x0b\x32\x11.btv.llm.v1.UsageH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\x42\t\n\x07payload\"Y\n\x05Usage\x12\x14\n\x0cinput_tokens\x18\x01 \x01(\x04\x12\x15\n\routput_tokens\x18\x02 \x01(\x04\x12\x11\n\tcache_hit\x18\x03 \x01(\x08\x12\x10\n\x08provider\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LLMREQUEST']._serialized_start=26
  _globals['_LLMREQUEST']._serialized_end=177
  _globals['_LLMCHUNK']._serialized_start=179
  _globals['_LLMCHUNK']._serialized_end=275
  _globals['_USAGE']._serialized_start=277
  _globals['_USAGE']._serialized_end=366
# @@protoc_insertion_point(module_scope)
