# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: promptforge.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'promptforge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11promptforge.proto\x12\x12\x62tv.promptforge.v1\"\x0f\n\rHealthRequest\"0\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\t\"\x1d\n\x0bLintRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"*\n\tLintIssue\x12\x0c\n\x04rule\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"Y\n\nLintReport\x12\r\n\x05score\x18\x01 \x01(\x01\x12\r\n\x05grade\x18\x02 \x01(\t\x12-\n\x06issues\x18\x03 \x03(\x0b\x32\x1d.btv.promptforge.v1.LintIssue\"\x90\x01\n\rRenderRequest\x12\x11\n\tgenerator\x18\x01 \x01(\t\x12=\n\x06\x66ields\x18\x02 \x03(\x0b\x32-.btv.promptforge.v1.RenderRequest.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\" \n\x0eRenderResponse\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"T\n\x0eGeneratorField\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x10\n\x08required\x18\x03 \x01(\x08\x12\x13\n\x0bplaceholder\x18\x04 \x01(\t\"c\n\rGeneratorInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x32\n\x06\x66ields\x18\x03 \x03(\x0b\x32\".btv.promptforge.v1.GeneratorField\"\x17\n\x15ListGeneratorsRequest\"O\n\x16ListGeneratorsResponse\x12\x35\n\ngenerators\x18\x01 \x03(\x0b\x32!.btv.promptforge.v1.GeneratorInfo2\xe8\x02\n\x12PromptForgeService\x12O\n\x06Health\x12!.btv.promptforge.v1.HealthRequest\x1a\".btv.promptforge.v1.HealthResponse\x12G\n\x04Lint\x12\x1f.btv.promptforge.v1.LintRequest\x1a\x1e.btv.promptforge.v1.LintReport\x12O\n\x06Render\x12!.btv.promptforge.v1.RenderRequest\x1a\".btv.promptforge.v1.RenderResponse\x12g\n\x0eListGenerators\x12).btv.promptforge.v1.ListGeneratorsRequest\x1a*.btv.promptforge.v1.ListGeneratorsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'promptforge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RENDERREQUEST_FIELDSENTRY']._loaded_options = None
  _globals['_RENDERREQUEST_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHREQUEST']._serialized_start=41
  _globals['_HEALTHREQUEST']._serialized_end=56
  _globals['_HEALTHRESPONSE']._serialized_start=58
  _globals['_HEALTHRESPONSE']._serialized_end=106
  _globals['_LINTREQUEST']._serialized_start=108
  _globals['_LINTREQUEST']._serialized_end=137
  _globals['_LINTISSUE']._serialized_start=139
  _globals['_LINTISSUE']._serialized_end=181
  _globals['_LINTREPORT']._serialized_start=183
  _globals['_LINTREPORT']._serialized_end=272
  _globals['_RENDERREQUEST']._serialized_start=275
  _globals['_RENDERREQUEST']._serialized_end=419
  _globals['_RENDERREQUEST_FIELDSENTRY']._serialized_start=374
  _globals['_RENDERREQUEST_FIELDSENTRY']._serialized_end=419
  _globals['_RENDERRESPONSE']._serialized_start=421
  _globals['_RENDERRESPONSE']._serialized_end=453
  _globals['_GENERATORFIELD']._serialized_start=455
  _globals['_GENERATORFIELD']._serialized_end=539
  _globals['_GENERATORINFO']._serialized_start=541
  _globals['_GENERATORINFO']._serialized_end=640
  _globals['_LISTGENERATORSREQUEST']._serialized_start=642
  _globals['_LISTGENERATORSREQUEST']._serialized_end=665
  _globals['_LISTGENERATORSRESPONSE']._serialized_start=667
  _globals['_LISTGENERATORSRESPONSE']._serialized_end=746
  _globals['_PROMPTFORGESERVICE']._serialized_start=749
  _globals['_PROMPTFORGESERVICE']._serialized_end=1109
# @@protoc_insertion_point(module_scope)
