# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import core_pb2 as core__pb2
from . import llm_pb2 as llm__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoreServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/forge.core.v1.CoreService/Generate',
                request_serializer=llm__pb2.LlmRequest.SerializeToString,
                response_deserializer=llm__pb2.LlmChunk.FromString,
                _registered_method=True)
        self.RunTool = channel.unary_unary(
                '/forge.core.v1.CoreService/RunTool',
                request_serializer=core__pb2.ToolCall.SerializeToString,
                response_deserializer=core__pb2.ToolResult.FromString,
                _registered_method=True)
        self.AppendLedger = channel.unary_unary(
                '/forge.core.v1.CoreService/AppendLedger',
                request_serializer=core__pb2.LedgerAppend.SerializeToString,
                response_deserializer=core__pb2.LedgerAck.FromString,
                _registered_method=True)
        self.Recall = channel.unary_unary(
                '/forge.core.v1.CoreService/Recall',
                request_serializer=core__pb2.RecallRequest.SerializeToString,
                response_deserializer=core__pb2.RecallResponse.FromString,
                _registered_method=True)
        self.Remember = channel.unary_unary(
                '/forge.core.v1.CoreService/Remember',
                request_serializer=core__pb2.RememberRequest.SerializeToString,
                response_deserializer=core__pb2.RememberAck.FromString,
                _registered_method=True)
        self.RequestPermission = channel.unary_unary(
                '/forge.core.v1.CoreService/RequestPermission',
                request_serializer=core__pb2.PermissionRequest.SerializeToString,
                response_deserializer=core__pb2.PermissionDecision.FromString,
                _registered_method=True)


class CoreServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Geração LLM via gateway (streaming de chunks).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTool(self, request, context):
        """Execução de ferramenta sujeita ao motor de permissões.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendLedger(self, request, context):
        """Anexa entrada ao ledger append-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recall(self, request, context):
        """Memória do squad persistida no forge-store.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestPermission(self, request, context):
        """Pedido de permissão/escalonamento HITL (decisão vem da TUI).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=llm__pb2.LlmRequest.FromString,
                    response_serializer=llm__pb2.LlmChunk.SerializeToString,
            ),
            'RunTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTool,
                    request_deserializer=core__pb2.ToolCall.FromString,
                    response_serializer=core__pb2.ToolResult.SerializeToString,
            ),
            'AppendLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendLedger,
                    request_deserializer=core__pb2.LedgerAppend.FromString,
                    response_serializer=core__pb2.LedgerAck.SerializeToString,
            ),
            'Recall': grpc.unary_unary_rpc_method_handler(
                    servicer.Recall,
                    request_deserializer=core__pb2.RecallRequest.FromString,
                    response_serializer=core__pb2.RecallResponse.SerializeToString,
            ),
            'Remember': grpc.unary_unary_rpc_method_handler(
                    servicer.Remember,
                    request_deserializer=core__pb2.RememberRequest.FromString,
                    response_serializer=core__pb2.RememberAck.SerializeToString,
            ),
            'RequestPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestPermission,
                    request_deserializer=core__pb2.PermissionRequest.FromString,
                    response_serializer=core__pb2.PermissionDecision.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forge.core.v1.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forge.core.v1.CoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/forge.core.v1.CoreService/Generate',
            llm__pb2.LlmRequest.SerializeToString,
            llm__pb2.LlmChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.core.v1.CoreService/RunTool',
            core__pb2.ToolCall.SerializeToString,
            core__pb2.ToolResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.core.v1.CoreService/AppendLedger',
            core__pb2.LedgerAppend.SerializeToString,
            core__pb2.LedgerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.core.v1.CoreService/Recall',
            core__pb2.RecallRequest.SerializeToString,
            core__pb2.RecallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.core.v1.CoreService/Remember',
            core__pb2.RememberRequest.SerializeToString,
            core__pb2.RememberAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forge.core.v1.CoreService/RequestPermission',
            core__pb2.PermissionRequest.SerializeToString,
            core__pb2.PermissionDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
